---
title: "R para ciencia de datos - Ejercicios"
author: "Noelí D'Alessio"
date: "4/24/2020"
output: html_document
---

```{r}
library(tidyverse)
library(datos)
```

## 5.2. Encuentra los vuelos que:

5.2.1 Tuvieron un retraso de llegada de más de dos horas:
```
filter(vuelos, llegada_programada >= 120)
``` 
5.2.2 Volaron a Houston (IAH oHOU):
```
filter(vuelos, destino %in% c("IAH", "HOU"))
```
5.2.3 Fueron operados por United, American o Delta:
```
filter(vuelos, aerolinea %in% c("UA", "AA","DL"))
```
5.2.4 Partieron en invierno (julio, agosto y septiembre):
```
filter(vuelos, mes %in% c(7, 8, 9))
filter(vuelos, mes %in% 7:9)
```
5.2.5 Llegaron más de dos horas tarde, pero no salieron tarde
```
filter(vuelos, atraso_salida > 120 & atraso_llegada <= 0)
```
5.2.6 Se retrasaron por lo menos una hora, pero repusieron más de 30 minutos en vuelo
```
filter(vuelos, atraso_salida >= 60, atraso_salida - atraso_llegada > 30)
```
5.2.7 Partieron entre la medianoche y las 6 a.m. (incluyente)
```
summary(vuelos$horario_salida)
```
El horario de salida de los aviones está representado así 00.20 = 020, 1am = 100, 6am = 600, 5pm = 1700, +++ 00.00 = 2400. Por lo tanto, no podemos hacer simplemente dep_time < 600. 
```
filter(vuelos, horario_salida  <= 600 | horario_salida == 2400)
```
5.2.8 Otra función de dplyr que es útil para usar filtros es between(). ¿Qué hace? ¿Puedes usarla para simplificar el código necesario para responder a los desafíos anteriores?
```
filter(vuelos, between(mes, 7, 9))
```
5.2.9 ¿Cuántos vuelos tienen datos faltantes en horario_salida? ¿Qué otras variables tienen valores faltantes? ¿Qué representan estas filas?
```
sum(is.na(vuelos$horario_salida))
vuelos_NA_salida <- filter(vuelos, is.na(horario_salida))
```
Hay 8255 vuelos con datos faltantes.Las variables horario_llegada, atraso_salida, atraso_llegada, codigo_cola, tiempo_vuelo también tienen datos faltantes. Representan vuelos cancelados.


5.2.10 ¿Por qué NA ^ 0 no es faltante? ¿Por qué NA | TRUE no es faltante? ¿Por qué FALSE & NA no es faltante? ¿Puedes descubrir la regla general? (¡NA * 0 es un contraejemplo complicado!)

En R NA^0 es igual a 1. Esto es porque si reemplazamos NA por cualquier número, dará 1.
b. En este caso NA representa un valor lógico, es decir, TRUE o FALSE. En cualquiera de los casos el resultado será TRUE.
F | T = T , T | T = T.
De manera similar, FALSE & NA, seleccionará aquellos casos que cumplan la condición FALSE. 

## 5.3 Arrange
5.3.1 ¿Cómo podrías usar arrange() para ordenar todos los valores faltantes al comienzo? (Sugerencia: usa is.na()). 
```
arrange(vuelos, (is.na(horario_salida)), horario_salida)
```
La función is.na coloca los valores faltantes al final. 
```
desc(is.na(horario_salida)), horario_salida 
```
5.3.2  Ordena vuelos para encontrar los vuelos más retrasados. 
```
arrange(vuelos, desc(atraso_salida))
```
Encuentra los vuelos que salieron más temprano.
```
arrange(vuelos, atraso_salida) 
```
5.3.3 Ordena vuelos para encontrar los vuelos más rápidos.
```
vuelos_velocidad <- mutate(vuelos, velocidad = distancia/(tiempo_vuelo*60))
vuelos_velocidad <- arrange(vuelos_velocidad, velocidad)
vuelos_velocidad <- select(vuelos_velocidad, velocidad, distancia, tiempo_vuelo, vuelo, origen, 
                           destino, anio, mes, dia)
```
5.3.4 4. ¿Cuáles vuelos viajaron más tiempo? ¿Cuál viajó menos tiempo?
Los que viajaron menos tiempo en cuanto a distancia: 
```
arrange(vuelos, distancia)
```
Los que viajaron más tiempo en cuanto a distancia:
```
arrange(vuelos, desc(distancia))
```
Los que viajaron menos cantidad de tiempo en cuanto a horas de vuelos:
```
arrange(vuelos, tiempo_vuelo)
```
Los que viajaron mayor cantidad de horas de vuelo:
```
arrange(vuelos, desc(tiempo_vuelo))
```

##5.4 Select
5.4.1 Haz una lluvia de ideas sobre tantas maneras como sea posible para seleccionar horario_salida,atraso_salida,horario_llegada, yatraso_llegada de vuelos.
```
select(vuelos, horario_salida, atraso_salida, horario_llegada, atraso_llegada)
select(vuelos, starts_with("horario"), starts_with("atraso"))
select(vuelos, ends_with("salida"), ends_with("llegada"))
select(vuelos, contains("horar"), contains("atr"))
variables_seleccionadas <- c("horario_salida", "horario_llegada", "atraso_salida", "atraso_llegada")
select(vuelos, one_of(variables_seleccionadas))
select(vuelos, matches("horario$|atraso$"))
```
5.4.2 ¿Qué sucede si incluyes el nombre de una variable varias veces en una llamada a select()?
```
select(vuelos, horario_salida, horario_salida)
```
No sucede nada, solo se muestra una vez la variable repetida. 

5.4.3 ¿Qué hace la función one_of()? ¿Por qué podría ser útil en conjunto con este vector?

one_of permite seleccionar las variables que combinan con los nombres de cierto vector de caracteres. Puede ser útil almacenar las variables que queremos en n vector, para agregar o quitar en el vector. También es útil utilizar on_of ya que si escribimos mal una variable nos avisaría que esa variable no existe.






                           







